#!/bin/sh 


export XDG_CONFIG_HOME="$HOME/.config"

export MANSECT="2:1:3:7:8:9:3:4:5"
export MPD_PORT="6601"

xrandr --output DVI-I-3 --right-of DVI-I-0

exec xset r rate 200 60 &
exec redshift -l 48.8:2.3 &
exec xscreensaver -no-splash &
exec ssh-agent > /home/arkadefr/ssh-agent.sh &
exec synology-cloud-station &
exec awesome
